
--h2_indexes.sql

--Copyright (c) 1995-2016, The University of Sheffield. See the file
--COPYRIGHT.txt in the software or at
--http://gate.ac.uk/gate/COPYRIGHT.txt

--This file is part of Bio-YODIE (see 
--https://gate.ac.uk/applications/bio-yodie.html), and is free 
--software, licenced under the GNU Affero General Public License
--Version 3, 19 November 2007

--A copy of this licence is included in the distribution in the file
--LICENSE-AGPL3.html, and is also available at
--http://www.gnu.org/licenses/agpl-3.0-standalone.html

--G. Gorrell, 26 September 2016




CREATE INDEX X_MRCONSO_CUI ON MRCONSO(CUI);

ALTER TABLE MRCONSO ADD CONSTRAINT X_MRCONSO_PK  PRIMARY KEY (AUI);

CREATE INDEX X_MRCONSO_STR ON MRCONSO(STR);

CREATE INDEX X_MRCONSO_SUI ON MRCONSO(SUI);

CREATE INDEX X_MRCONSO_LUI ON MRCONSO(LUI);

CREATE INDEX X_MRCONSO_CODE ON MRCONSO(CODE);

CREATE INDEX X_MRCONSO_SAB_TTY ON MRCONSO(SAB,TTY);

CREATE INDEX X_MRCONSO_SCUI ON MRCONSO(SCUI);

CREATE INDEX X_MRCONSO_SDUI ON MRCONSO(SDUI);

CREATE INDEX X_MRCONSO_ISPREF ON MRCONSO(ISPREF);

CREATE INDEX X_MRDEF_CUI ON MRDEF(CUI);

CREATE INDEX X_MRDEF_AUI ON MRDEF(AUI);

ALTER TABLE MRDEF ADD CONSTRAINT X_MRDEF_PK  PRIMARY KEY (ATUI);

CREATE INDEX X_MRDEF_SAB ON MRDEF(SAB);

CREATE INDEX X_MRHIER_CUI ON MRHIER(CUI);

CREATE INDEX X_MRHIER_AUI ON MRHIER(AUI);

CREATE INDEX X_MRHIER_SAB ON MRHIER(SAB);

CREATE INDEX X_MRHIER_PAUI ON MRHIER(PAUI);

ALTER TABLE MRRANK ADD CONSTRAINT X_MRRANK_PK  PRIMARY KEY (SAB,TTY);

CREATE INDEX X_MRREL_CUI1 ON MRREL(CUI1);

CREATE INDEX X_MRREL_AUI1 ON MRREL(AUI1);

CREATE INDEX X_MRREL_CUI2 ON MRREL(CUI2);

CREATE INDEX X_MRREL_AUI2 ON MRREL(AUI2);

ALTER TABLE MRREL ADD CONSTRAINT X_MRREL_PK  PRIMARY KEY (RUI);

CREATE INDEX X_MRREL_SAB ON MRREL(SAB);

ALTER TABLE MRSAB ADD CONSTRAINT X_MRSAB_PK  PRIMARY KEY (VSAB);

CREATE INDEX X_MRSAB_RSAB ON MRSAB(RSAB);

CREATE INDEX X_MRSAT_CUI ON MRSAT(CUI);

CREATE INDEX X_MRSAT_METAUI ON MRSAT(METAUI);

ALTER TABLE MRSAT ADD CONSTRAINT X_MRSAT_PK  PRIMARY KEY (ATUI);

CREATE INDEX X_MRSAT_SAB ON MRSAT(SAB);

CREATE INDEX X_MRSAT_ATN ON MRSAT(ATN);

CREATE INDEX X_MRSTY_CUI ON MRSTY(CUI);

ALTER TABLE MRSTY ADD CONSTRAINT X_MRSTY_PK  PRIMARY KEY (ATUI);

CREATE INDEX X_MRSTY_STY ON MRSTY(STY);

CREATE INDEX X_MRXNW_ENG_NWD ON MRXNW_ENG(NWD);

CREATE INDEX X_MRXW_ENG_WD ON MRXW_ENG(WD);

CREATE INDEX X_AMBIGSUI_SUI ON AMBIGSUI(SUI);

CREATE INDEX X_AMBIGLUI_LUI ON AMBIGLUI(LUI);

CREATE INDEX X_MRAUI_CUI2 ON MRAUI(CUI2);

CREATE INDEX X_MRCUI_CUI2 ON MRCUI(CUI2);

